import type { Plan } from '../lib/model';
import { money } from '../lib/format';
import { useAssessment } from '../state/AssessmentContext';
import { AssessmentSummary } from './AssessmentSummary';
import './report.css';

interface Props { plan: Plan; savedAt: number | null; onAdjust: () => void; onSave: () => void; onCompare: () => void; }
export function Review({ plan, savedAt, onAdjust, onSave, onCompare }: Props) {
  const { household, assessment, loading, error } = useAssessment();
  return <div className="review fade">
    <header className="review-head"><div><p className="eyebrow">Review &amp; Plan · {plan.name}</p><h1 className="page-title">A clearer view of your protection.</h1><p className="page-sub">Review your current estimate, compare coverage characteristics, and save a plan to come back to.</p></div><div className="review-actions"><button className="btn primary lg" onClick={onAdjust}>Adjust Plan</button><button className="btn secondary lg" onClick={onSave}>{savedAt ? 'Saved' : 'Save Plan'}</button><button className="btn ghost lg" onClick={onCompare}>Compare plans</button></div></header>
    <AssessmentSummary />
    <section className="tvp">
      <article className="panel tvp-card"><p className="tvp-kicker">Term life insurance</p><h2 className="tvp-title">A defined period of protection</h2><ul className="tvp-points"><li>Provides coverage for a specified period.</li><li>Useful to discuss when obligations have a known end date.</li><li>Check the policy's renewal and conversion provisions.</li><li>Coverage amounts and premiums require an actual insurer quote.</li></ul><div className="tvp-you"><span>Your timeline illustration</span><strong>{plan.timeline.termYears}-year window shown for comparison</strong></div><a className="source-link" href="https://www.lincolnfinancial.com/public/individuals/products/lifeinsurance/termlife" target="_blank" rel="noreferrer">Read Lincoln Financial's term overview ↗</a></article>
      <article className="panel tvp-card"><p className="tvp-kicker">Permanent life insurance</p><h2 className="tvp-title">Protection intended for longer needs</h2><ul className="tvp-points"><li>Can continue for life when policy requirements are met.</li><li>May include cash value, depending on the policy.</li><li>Costs, guarantees and access to cash value vary by product.</li><li>Review policy details with a licensed professional.</li></ul><div className="tvp-you"><span>Questions to consider</span><strong>Which needs continue beyond a fixed term?</strong></div><a className="source-link" href="https://www.lincolnfinancial.com/public/individuals/products/lifeinsurance/permanentlife" target="_blank" rel="noreferrer">Read Lincoln Financial's permanent overview ↗</a></article>
    </section>
    <p className="tvp-note">LifeCast does not select a policy or estimate a premium. Use the plan to prepare for a coverage conversation.</p>
    {household && assessment && !loading && !error && <section className="panel tradeoffs"><h2 className="section-heading">The facts behind this plan</h2><div className="facts"><div><span>Children entered</span><strong>{household.children.length}</strong></div><div><span>Annual income</span><strong>{money(household.person.income)}</strong></div><div><span>Current debts</span><strong>{money(household.debts.mortgage + household.debts.other)}</strong></div><div><span>Current coverage gap</span><strong>{money(assessment.coverageGap)}</strong></div></div><div className="tradeoff-grid"><div className="tradeoff"><h3 className="sub-heading">Near-term responsibilities</h3><p>Review ongoing income support, outstanding debts, education funding and the coverage already in place. You can change each input in Financial Planning.</p></div><div className="tradeoff"><h3 className="sub-heading">What may change later</h3><p>You have {plan.lifeEvents.length} planned life event{plan.lifeEvents.length === 1 ? '' : 's'}. Explore their illustrative effects in Life Events, then return to the Report tab for the current calculator result and its assumptions.</p></div></div></section>}
    <section className="panel review-readiness"><h2 className="section-heading">Before you decide</h2><ul><li>Check the income support period and the ages used for your children.</li><li>Confirm whether employer coverage continues when you change jobs.</li><li>Compare costs, exclusions, guarantees and eligibility using actual policy documents.</li></ul></section>
    <p className="disclaimer">Save Plan stores this plan in this browser on this device. CalcXML currently uses a documented sample connection. This is an educational estimate, not a quote or recommendation.</p>
  </div>;
}
